# Generated by Django 4.1.7 on 2023-04-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
