# Generated by Django 4.1.7 on 2023-04-21 01:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contato_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='read',
            field=models.BooleanField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
