# Generated by Django 4.1.7 on 2023-04-21 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0003_alter_contato_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='read_contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
