# Generated by Django 4.1.7 on 2023-04-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contato_read_read_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
