# Generated by Django 4.1.5 on 2023-03-09 02:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='review_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 8, 23, 2, 34, 85979))),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Eletrodoméstico', 'Eletrodoméstico'), ('Beleza', 'Beleza'), ('Acessórios', 'Acessórios'), ('Roupas', 'Roupas')], default='Categoria', max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('observation', models.TextField(max_length=150)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='image/')),
                ('review', models.ManyToManyField(to='index.review_person')),
            ],
        ),
    ]
