# Generated by Django 4.1.5 on 2023-03-09 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, to='index.review_person'),
        ),
        migrations.AlterField(
            model_name='review_person',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 8, 23, 10, 16, 976265)),
        ),
    ]
