# Generated by Django 4.1.5 on 2023-03-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_review_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_person',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
