# Generated by Django 4.1.5 on 2023-03-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_review_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(to='index.review_person'),
        ),
    ]
