# Generated by Django 4.1.5 on 2023-03-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
