# Generated by Django 4.1.5 on 2023-03-10 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_remove_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_person',
            name='product_review',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.product'),
        ),
    ]
