# Generated by Django 4.1.5 on 2023-03-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_carrinho_car_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_person',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
