# Generated by Django 4.1.5 on 2023-03-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_review_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_person',
            name='image',
        ),
    ]
