# Generated by Django 4.1.7 on 2023-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
