# Generated by Django 4.1.7 on 2023-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='car_product',
            field=models.ManyToManyField(blank=True, to='index.product'),
        ),
    ]
