# Generated by Django 4.1.7 on 2023-04-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_product_color_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='Não informar', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Não informar', 'Não informar'), ('pp', 'pp'), ('p', 'p'), ('m', 'm'), ('g', 'g'), ('gg', 'gg'), ('xgg', 'xgg')], default='size', max_length=13),
        ),
    ]
