# Generated by Django 4.1.7 on 2023-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Eletrodoméstico', 'Eletrodoméstico'), ('Beleza', 'Beleza'), ('Acessórios', 'Acessórios'), ('Roupas', 'Roupas'), ('Fantasias', 'Fantasias'), ('Computador', 'Computador')], default='Categoria', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=250, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='observation',
            field=models.TextField(max_length=150, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Não informar', 'Não informar'), ('pp', 'pp'), ('p', 'p'), ('m', 'm'), ('g', 'g'), ('gg', 'gg'), ('xgg', 'xgg')], default='size', max_length=13, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='0', verbose_name='Estoque'),
        ),
    ]
