# Generated by Django 4.1.7 on 2023-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_alter_product_active_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Não informar', 'Não informar'), ('Preto', 'Preto'), ('Branco', 'Branco'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde')], default='Não informar', max_length=15),
        ),
    ]
